apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: APP_NAME
  description: The name for the application
  displayName: Application Name
  required: true
  value: hulking-pump
- name: WELCOME_IMAGE_NAME
  description: The Welcome App's image name
  displayName: Image Name
  required: true
  value: fabric8/launcher-creator-welcome-app
- name: WELCOME_IMAGE_TAG
  description: The Welcome App's image tag
  displayName: Image Tag
  required: true
  value: latest
- name: WELCOME_APP_CONFIG
  description: The configuration for the welcome app
  displayName: Welcome App Configuration
  required: true
  value: |-
    {
      "parts": [{
        "capabilities": [{
          "module": "capability-web-app",
          "props": {},
          "extra": {
            "category": "frontend"
          }
        }],
        "shared": {
          "runtime": {
            "name": "vuejs",
            "version": "community"
          }
        },
        "extra": {
          "runtimeInfo": {
            "enumInfo": {
              "id": "vuejs",
              "name": "Vue.js",
              "description": "The Progressive JavaScript Framework",
              "icon": "data:image/svg+xml,%3c%3fxml version='1.0' encoding='UTF-8' standalone='no'%3f%3e %3csvg xmlns:dc='http://purl.org/dc/elements/1.1/' xmlns:cc='http://creativecommons.org/ns%23' xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns%23' xmlns:svg='http://www.w3.org/2000/svg' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 400' height='400' width='400' xml:space='preserve' id='svg2' version='1.1'%3e%3cmetadata id='metadata8'%3e%3crdf:RDF%3e%3ccc:Work rdf:about=''%3e%3cdc:format%3eimage/svg%2bxml%3c/dc:format%3e%3cdc:type rdf:resource='http://purl.org/dc/dcmitype/StillImage' /%3e%3c/cc:Work%3e%3c/rdf:RDF%3e%3c/metadata%3e%3cdefs id='defs6' /%3e%3cg transform='matrix(1.3333333%2c0%2c0%2c-1.3333333%2c0%2c400)' id='g10'%3e%3cg transform='translate(178.0626%2c235.0086)' id='g12'%3e%3cpath id='path14' style='fill:%234dba87%3bfill-opacity:1%3bfill-rule:nonzero%3bstroke:none' d='M 0%2c0 -22.669%2c-39.264 -45.338%2c0 h -75.491 L -22.669%2c-170.017 75.491%2c0 Z' /%3e%3c/g%3e%3cg transform='translate(178.0626%2c235.0086)' id='g16'%3e%3cpath id='path18' style='fill:%23435466%3bfill-opacity:1%3bfill-rule:nonzero%3bstroke:none' d='M 0%2c0 -22.669%2c-39.264 -45.338%2c0 H -81.565 L -22.669%2c-102.01 36.227%2c0 Z' /%3e%3c/g%3e%3c/g%3e%3c/svg%3e",
              "metadata": {
                "categories": ["frontend"],
                "language": "javascript",
                "website": "https://vuejs.org"
              }
            },
            "image": "nodeshift/centos7-s2i-web-app",
            "service": "hulking-pump-frontend",
            "route": "hulking-pump-frontend"
          },
          "category": "frontend"
        },
        "subFolderName": "frontend"
      }, {
        "capabilities": [{
          "module": "capability-health",
          "props": {},
          "extra": {
            "category": "backend"
          }
        }, {
          "module": "capability-database",
          "props": {
            "databaseType": "postgresql"
          },
          "extra": {
            "category": "backend",
            "databaseInfo": {
              "image": "postgresql",
              "service": "hulking-pump-backend-database-bind"
            },
            "sourceMapping": {
              "dbEndpoint": "src/main/java/io/openshift/booster/database/CrudApplication.java"
            }
          }
        }],
        "shared": {
          "runtime": {
            "name": "vertx",
            "version": "redhat"
          },
          "maven": {
            "groupId": "org.openshift.appgen",
            "artifactId": "my-app",
            "version": "1.0.0"
          }
        },
        "extra": {
          "runtimeInfo": {
            "enumInfo": {
              "id": "vertx",
              "name": "Vert.x",
              "description": "A tool-kit for building reactive applications on the JVM.",
              "icon": "data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 640 280'%3E%3Cpath fill='%23022B37' d='M107 170.8L67.7 72H46.9L100 204h13.9L167 72h-20.4zm64 33.2h80v-20h-61v-37h60v-19h-60V91h61V72h-80zm180.1-90.7c0-21-14.4-42.3-43.1-42.3h-48v133h19V91h29.1c16.1 0 24 11.1 24 22.4 0 11.5-7.9 22.6-24 22.6H286v9.6l48 58.4h24.7L317 154c22.6-4 34.1-22 34.1-40.7m56.4 90.7v-1c0-6 1.7-11.7 4.5-16.6V91h39V71h-99v20h41v113h14.5z'/%3E%3Cpath fill='%23623C94' d='M458 203c0-9.9-8.1-18-18-18s-18 8.1-18 18 8.1 18 18 18 18-8.1 18-18M577.4 72h-23.2l-27.5 37.8L499.1 72h-40.4c12.1 16 33.6 46.8 47.8 66.3l-37 50.9c2 4.2 3.1 8.9 3.1 13.8v1H499l95.2-132h-16.8zm-19.7 81.5l-20.1 27.9 16.5 22.6h40.2c-9.6-13.7-24-33.3-36.6-50.5z'/%3E%3C/svg%3E",
              "metadata": {
                "categories": ["backend"],
                "language": "java",
                "website": "https://projects.eclipse.org/projects/rt.vertx"
              }
            },
            "image": "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift",
            "service": "hulking-pump-backend",
            "route": "hulking-pump-backend"
          },
          "category": "backend"
        },
        "subFolderName": "backend"
      }, {
        "capabilities": [{
          "module": "capability-welcome",
          "props": {},
          "extra": {
            "category": "support"
          }
        }],
        "shared": {},
        "extra": {
          "category": "support"
        },
        "subFolderName": "support"
      }],
      "application": "hulking-pump"
    }
- name: FRONTEND_SERVICE_NAME
  description: The frontend service name for the welcome app
  displayName: Frontend service name
  required: true
  value: hulking-pump-frontend
- name: BACKEND_SERVICE_NAME
  description: The backend service name for the welcome app
  displayName: Backend service name
  required: true
  value: hulking-pump-backend
- name: SOURCE_REPOSITORY_PROVIDER
  description: The source repository provider
  displayName: Source Provider
  value: GitHub
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
- name: OPENSHIFT_CONSOLE_URL
  description: The OpenShift Console URL for the application
  displayName: OpenShift Console URL
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: ${WELCOME_IMAGE_TAG}
      from:
        kind: DockerImage
        name: ${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}-welcome
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}-welcome
      spec:
        containers:
        - image: ${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}
          name: ${APP_NAME}-welcome
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 8M
            limits:
              cpu: 50m
              memory: 100Mi
          env:
          - name: WELCOME_APP_CONFIG
            value: ${WELCOME_APP_CONFIG}
          - name: OPENSHIFT_CONSOLE_URL
            value: ${OPENSHIFT_CONSOLE_URL}
          - name: SOURCE_REPOSITORY_PROVIDER
            value: ${SOURCE_REPOSITORY_PROVIDER}
          - name: SOURCE_REPOSITORY_URL
            value: ${SOURCE_REPOSITORY_URL}
          - name: FRONTEND_SERVICE_NAME
            value: ${FRONTEND_SERVICE_NAME}
          - name: BACKEND_SERVICE_NAME
            value: ${BACKEND_SERVICE_NAME}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}-welcome
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}-welcome:${WELCOME_IMAGE_TAG}
      type: ImageChange
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}-welcome
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
    annotations:
      console.alpha.openshift.io/overview-app-route: 'true'
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}-welcome
